{"uuid":"cea6d1f2-0517-4f93-af63-662b575fe256","historyId":"bb64faaafd43417050b861c7ceef59e9","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"runners.RunCategoryTests"},{"name":"testClass","value":"runners.RunCategoryTests"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"CucumberBaseProject"},{"name":"subSuite","value":"runners.RunCategoryTests"},{"name":"host","value":"DESKTOP-E482151"},{"name":"thread","value":"18212@DESKTOP-E482151.TestNG-PoolService-7(23)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [\"Category has been updated successfully\"] but found [Category has been updated successfully]","trace":"java.lang.AssertionError: expected [\"Category has been updated successfully\"] but found [Category has been updated successfully]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat stepdefinition.Category.CategoryStepdefs.theMessageDisplays(CategoryStepdefs.java:110)\r\n\tat âœ½.the message \"Category has been updated successfully\" displays(file:///D:/Learn-Automation-Testing/CucumberBaseProject/src/test/resources/features/Category/Category.feature:34)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"Manage Category\""},{"name":"arg0","value":"\"Update the Category existing\""}],"start":1722315157039,"stop":1722315183070}